$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot

function Read-ProjectFile([string]$relativePath) {
    return Get-Content -LiteralPath (Join-Path $projectRoot $relativePath) -Raw
}

function Require-Match([string]$text, [string]$pattern, [string]$message) {
    if ($text -notmatch $pattern) {
        throw $message
    }
}

function Require-NoMatch([string]$text, [string]$pattern, [string]$message) {
    if ($text -match $pattern) {
        throw $message
    }
}

$mergeHost = Read-ProjectFile 'merge_src\PluginPingMerge.cpp'
Require-Match $mergeHost 'case 0: return &m_directItem' 'DIRECT composite row must be item 0.'
Require-Match $mergeHost 'case 1: return &m_proxyItem' 'PROXY composite row must be item 1.'
Require-NoMatch $mergeHost 'case 2:|case 3:' 'The host must see exactly two composite rows.'
Require-Match $mergeHost 'case TMI_NAME:\s+return L"PluginPing"' 'The plugin name must remain PluginPing.'
Require-Match $mergeHost 'instance\.IsReady\(\) \? &instance : nullptr' 'Merged instance readiness guard is missing.'
Require-Match $mergeHost 'm_ping \? m_ping->GetItem\(0\) : nullptr' 'Ping bridge null guard is missing.'

$compositeItem = Read-ProjectFile 'merge_src\CompositeStatusItem.cpp'
$compositeHeader = Read-ProjectFile 'merge_src\CompositeStatusItem.h'
Require-Match $compositeItem 'L"PluginPingLocal"' 'DIRECT must preserve the original PluginPing item ID.'
Require-Match $compositeItem 'L"PluginPingRemote"' 'PROXY must preserve the original PluginPing item ID.'
Require-Match $compositeItem 'ipItem->DrawItem' 'Composite rows must draw their IP section.'
Require-Match $compositeItem 'probeItem->DrawItem' 'Composite rows must draw their TCP/UDP section.'
Require-Match $compositeItem 'MeasureCompositeWidth' 'Composite rows must use the shared section interface.'
Require-Match $compositeItem 'constexpr int kTrailingPadding96\s*=\s*6' 'Composite rows must reserve a stable outer trailing gap.'
Require-Match $compositeItem 'constexpr int kSectionGap96\s*=\s*6' 'Composite rows must define a stable IP/RTT fallback gap.'
Require-Match $compositeItem 'GetTextExtentPoint32W\(dc, L" ", 1, &size\)[\s\S]*?return size\.cx \* 2' 'IP/RTT spacing must use two spaces measured in the host font.'
Require-Match $compositeItem 'ipWidth \+ SectionGap\(dc\) \+ probeWidth \+ ScaledTrailingPadding\(dc\)' 'Section and trailing gaps must be included in the host-facing width.'
Require-Match $compositeItem 'const int contentWidth = w - trailingPadding' 'Child renderers must not paint into the composite trailing gap.'
Require-Match $compositeItem 'x \+ ipWidth \+ sectionGap' 'The compositor must own the blank region between IP and RTT.'
Require-NoMatch $compositeItem 'static_cast<pluginping::CPingStatusItem|static_cast<pluginnetwork::CNetworkStatusItem' 'Composite rows must not cast concrete child item types.'
Require-Match $compositeHeader '(?s)#define WIN32_LEAN_AND_MEAN.*#include <windows\.h>' 'Composite Windows headers must exclude legacy winsock.h.'

$status = Read-ProjectFile 'ping_src\src\StatusData.h'
$ipRenderer = Read-ProjectFile 'ping_src\src\Renderer.cpp'
$ipWorker = Read-ProjectFile 'ping_src\src\PluginPing.cpp'
$ipWorkerHeader = Read-ProjectFile 'ping_src\src\PluginPing.h'
$proxyIpPolicy = Read-ProjectFile 'ping_src\src\ProxyIpStatePolicy.h'
Require-NoMatch ($status + $ipRenderer + $ipWorker) '(?i)latencyMs|latencyDiagnostic|\bonline\b|ProbeHttpLatency|ProbeIcmpLatency' 'IP display still contains latency/online logic.'
Require-Match $ipWorker 'QueryCloudflareTraceIp' 'PROXY must use Cloudflare trace.'
Require-NoMatch $ipWorker 'QueryIpifyIp' 'PROXY fallback must remain removed.'
Require-Match $ipWorker 'SetProxyFailure\(diagnostic, runtime, output, ProxyFailureKind::Transient\)' 'Transient PROXY failures must preserve the last confirmed Cloudflare result.'
Require-Match $ipWorker 'if \(!proxyIdentity\.empty\(\)\)[\s\S]*?const LocalRemoteSnapshot latest[\s\S]*?proxyRawIp == latest\.local\.ipAddress\)[\s\S]*?SetProxyFailure\(proxy\.diagnostic, proxy, remote,[\s\S]*?ProxyFailureKind::RejectedRoute\)' 'Only a confirmed PROXY egress matching DIRECT may clear the identity.'
Require-Match $ipWorker 'proxyInterval = static_cast<unsigned long long>\(\s+\(std::max\)\(cfg\.remoteResolveIntervalMs, 1\)\)' 'PROXY retries must stay on the configured node-switch cadence.'
Require-NoMatch $ipWorker 'proxyInterval[\s\S]{0,160}cfg\.ipFailureBackoffMs' 'PROXY failures must not enter the DIRECT failure backoff.'
Require-Match $proxyIpPolicy 'kind == ProxyFailureKind::Transient && \(!ip\.empty\(\) \|\| displayAsnOnly\)' 'Transient failures must retain an existing confirmed PROXY identity, including loc=CN N/A.'
Require-Match $proxyIpPolicy 'ip\.clear\(\);[\s\S]*?country = L"--"' 'Rejected or initially unavailable PROXY identities must be cleared.'
Require-Match $ipWorker '_wcsicmp\(loc\.c_str\(\), L"CN"\)' 'PROXY loc=CN mapping is missing.'
Require-Match $ipWorker 'runtime\.displayAsnOnly = china;[\s\S]*?runtime\.ip = china \? L"" : ip[\s\S]*?runtime\.country = china \? L"N/A"' 'PROXY loc=CN must collapse ASN and IP to one N/A.'
Require-Match $ipWorker 'if \(!HasDisplayedItem\(\)\)\s+return;' 'Hidden IP rows must not start the worker.'
Require-Match $ipWorker 'EffectiveResolveInterval' 'IP failure backoff is not wired into scheduling.'
Require-Match $ipWorker 'runtime\.failures < cfg\.failThreshold' 'IP failure threshold is not applied.'
Require-Match $ipWorker 'copy = MakeTooltip\(\*snapshot, m_localItem\.LastDrawTick\(\) != 0,' 'IP tooltip must derive from the current snapshot and visible rows.'
Require-NoMatch ($ipWorker + $ipWorkerHeader) 'm_tooltip|m_tooltipMutex' 'The removed IP tooltip cache returned.'
Require-Match $ipWorker 'm_store\.UpdateLocal\(status\)[\s\S]*?m_store\.UpdateRemote\(status\)[\s\S]*?if \(cfg\.debugLog\)[\s\S]*?m_logMutex' 'IP snapshot publication must remain independent from optional log serialization.'
Require-NoMatch ($ipWorker + $ipWorkerHeader) 'm_publishMutex|publishLock' 'The removed IP publication lock returned.'
Require-NoMatch ((Read-ProjectFile 'ping_src\src\ConfigManager.cpp') + (Read-ProjectFile 'ping_src\src\ConfigManager.h') + (Read-ProjectFile 'network_src\src\ConfigManager.cpp') + (Read-ProjectFile 'network_src\src\ConfigManager.h')) 'EnsureLoaded|ReloadIfChanged' 'Removed two-step config reload APIs returned.'
Require-NoMatch ((Read-ProjectFile 'ping_src\src\ConfigManager.cpp') + (Read-ProjectFile 'ping_src\src\ConfigManager.h') + (Read-ProjectFile 'network_src\src\ConfigManager.cpp') + (Read-ProjectFile 'network_src\src\ConfigManager.h')) 'PluginConfig Get\(\) const|unsigned long long Generation\(\) const' 'Removed mutable config-copy and duplicate generation APIs returned.'
Require-Match $ipWorker '!primaryOk && QueryPconlineIp' 'DIRECT fallback must not run after a successful primary query.'
Require-Match $ipWorker 'if \(!primaryOk\)\s+diagnostic \+=' 'DIRECT diagnostics must only describe a fallback that actually ran.'
Require-NoMatch ($status + $ipRenderer + $ipWorker) 'IpDisplayTone|ipTone|primaryOk && fallbackOk' 'Dead split-source warning state returned.'
Require-Match $ipWorker '!proxyRawIp\.empty\(\) && cfg\.localDisplayIp\.empty\(\)[\s\S]{0,240}proxyRawIp == latest\.local\.ipAddress' 'PROXY must reject an egress matching the latest DIRECT baseline using the raw IP.'
Require-Match $ipWorker 'm_directHttpCancellation\.Cancel\(\)[\s\S]*?m_proxyHttpCancellation\.Cancel\(\)[\s\S]*?m_directWorker\.join\(\)[\s\S]*?m_proxyWorker\.join\(\)' 'IP shutdown must cancel both WinHTTP workers before joining.'
Require-Match $ipWorker 'std::thread\(&CPluginPing::DirectWorkerLoop[\s\S]*?std::thread\(&CPluginPing::ProxyWorkerLoop' 'DIRECT and PROXY HTTP requests must run on independent workers.'
Require-Match $ipWorker 'PublishWorkerFailure\(PingEndpoint::Local\)[\s\S]*?WaitForSingleObject\(m_wake, kIpWorkerRetryBackoffMs\)[\s\S]*?PublishWorkerFailure\(PingEndpoint::Remote\)[\s\S]*?WaitForSingleObject\(m_wake, kIpWorkerRetryBackoffMs\)' 'Each IP worker must recover independently with an interruptible retry delay.'
Require-NoMatch ($ipWorker + $ipWorkerHeader) '\bWorkerLoop\b|\bm_started\b|m_workerFailed|m_restartAttempts|m_nextRestartTick|m_startedTick|PublishSnapshot|PublishInitialSnapshot|CPluginPing::OnInitialize' 'The removed IP lifecycle layers returned.'
Require-Match $ipWorker 'awaiting DIRECT revalidation[\s\S]*?proxyIdentity\.clear\(\)' 'A changed PROXY identity must wait for a fresh DIRECT leak baseline before publication.'
Require-Match $ipWorker 'PublishEndpoint\(PingEndpoint::Local, local, cfg\);[\s\S]*?m_directRevalidateCompleted\.store' 'DIRECT revalidation completion must follow publication of the fresh result.'
Require-Match $ipWorker 'pendingRawIp = proxyRawIp;[\s\S]*?m_directRevalidateCompleted\.load\(\) >= pendingRevalidateRequest[\s\S]*?proxyIdentity = pendingIdentity;[\s\S]*?proxyRawIp = pendingRawIp;' 'A completed DIRECT validation must release the already confirmed PROXY identity without another successful trace.'
Require-Match $ipWorker 'RefreshDirect\([\s\S]*?ObserveLocalRouteNow\(\);[\s\S]*?NetworkEpoch\(\) != requestNetworkEpoch' 'DIRECT results crossing a network generation must be discarded.'
Require-Match $ipWorker 'RefreshProxy\([\s\S]*?ObserveLocalRouteNow\(\);[\s\S]*?NetworkEpoch\(\) != requestNetworkEpoch' 'PROXY results crossing a network generation must be discarded.'
Require-Match $ipWorker 'const bool proxyIdentityNeeded =\s+IsRecentlyDisplayed\(m_localItem\.LastDrawTick\(\), cfg, now\) \|\|\s+IsRecentlyDisplayed\(m_remoteItem\.LastDrawTick\(\), cfg, now\)' 'The TCP channel travels the proxy route, so a DIRECT-only layout must still observe node changes.'
Require-Match $ipWorker 'const bool refreshProxy = proxyIdentityNeeded' 'PROXY identity refresh must follow the probe consumers, not only the PROXY row.'
Require-Match $ipWorker 'ProxyFailureKind::RejectedRoute\);[\s\S]*?proxyIdentity = pluginping_shared::MakeDirectLeakIdentity\(proxyRawIp\)' 'A rejected PROXY egress must retain its raw IP while changing route status.'
Require-Match $ipWorker 'routeEpoch\.PublishProxyIdentity\(proxyIdentity\);\s+lastProxy = GetTickCount64\(\)' 'Exactly one proxy identity must be published per refresh, after the rejection verdict.'

$routeEpoch = Read-ProjectFile 'shared_src\RouteEpoch.cpp'
$routeEpochHeader = Read-ProjectFile 'shared_src\RouteEpoch.h'
Require-Match $routeEpoch 'if \(identity\.empty\(\)\)[\s\S]*?return m_epoch\.load' 'An unconfirmed observation must never advance the route epoch.'
Require-Match $routeEpoch 'm_proxyEpoch\.fetch_add\(1' 'Every newly confirmed proxy identity, including the first, must invalidate transports opened before confirmation.'
Require-Match $routeEpoch 'if \(ip\.empty\(\)\)\s+return std::wstring\(\)' 'An identity without an egress IP must fail closed.'
Require-Match $routeEpoch 'GetBestRoute2' 'Local best-route changes must be observed through the Windows route table.'
Require-Match $routeEpoch 'unsigned long long RouteEpoch::ObserveLocalRoute\(\)' 'The bounded local-route observer is missing.'
Require-Match $routeEpochHeader 'MakeDirectLeakIdentity' 'The direct-leak identity helper is missing.'
Require-Match $ipWorker 'identityOut = pluginping_shared::MakeProxyIdentity\(ip\);[\s\S]*?const bool china' 'The node identity must be taken from the raw trace, before the loc=CN display collapse.'

$provider = Read-ProjectFile 'ping_src\src\PublicIpProvider.cpp'
Require-NoMatch ((Read-ProjectFile 'ping_src\src\PublicIpProvider.h') + $provider) 'fallbackUsed' 'NetworkStage already identifies fallback diagnostics; a second flag is redundant.'
Require-Match $provider 'HttpGet\(L"www\.cloudflare\.com", L"/cdn-cgi/trace"' 'Cloudflare trace endpoint changed.'
Require-Match $provider 'const ProxySettings proxy = ResolveProxySettings\(cfg, proxyPolicy\);[\s\S]*?HINTERNET hSession = WinHttpOpen[\s\S]*?WinHttpHandleScope sessionScope\(hSession\);' 'Each public-IP request must own its WinHTTP session lifetime.'
Require-NoMatch $provider 'WinHttpSessionCache|GetSharedHttpSession|class ProxyCache|GetCachedProxySettings' 'Public-IP routing must not stack caches or share evictable sessions across workers.'
Require-Match $provider 'ParseCloudflareTraceBody' 'Cloudflare trace body parser is not shared and testable.'
Require-NoMatch $provider 'QueryIpifyIp|ProbeHttpLatency|ProbeIcmpLatency|ResolveTargetIpv4|MmdbReader' 'Removed IP/latency/Geo code returned.'
Require-Match $provider 'ResolveRoutePlan' 'IP HTTP must consume the shared route plan.'
Require-Match $provider 'class RequestHandleScope' 'IP WinHTTP request handles must use exception-safe ownership.'
Require-Match $provider 'WinHttpOpen\(kPluginPingUserAgent,[\s\S]*?WINHTTP_NO_PROXY_BYPASS' 'PROXY Cloudflare requests must not honor a direct bypass.'
Require-Match $provider 'if \(proxy\.unavailable\)[\s\S]*?return out \+ L" unavailable"' 'Unavailable proxy diagnostics must fail closed before direct-route text.'
Require-Match $provider 'proxyPolicy == EndpointProxyPolicy::ConfiguredProxy[\s\S]*?WINHTTP_DISABLE_KEEP_ALIVE' 'Cloudflare trace must not reuse a tunnel belonging to the previous proxy node.'

$pingConfig = Read-ProjectFile 'ping_src\src\ConfigManager.cpp'
Require-Match $pingConfig 'kIniFileName = L"PluginPing\.ini"' 'IP config must retain the PluginPing name.'
Require-NoMatch $pingConfig '\[Geo\]|PingInterval|RemoteTarget' 'Legacy IP configuration schema returned.'
Require-Match $pingConfig 'L"Style", L"CompactMode"' 'IP rows must read the shared compact mode.'

$networkConfig = Read-ProjectFile 'network_src\src\ConfigManager.h'
Require-Match $networkConfig 'udpEchoServer = L"sg\.falsemeet\.site:3478"' 'UDP echo primary changed.'
Require-Match $networkConfig 'udpFallbackStunServer = L"stun\.cloudflare\.com:3478"' 'UDP STUN fallback changed.'

$networkWorker = Read-ProjectFile 'network_src\src\PluginNetwork.cpp'
Require-Match $networkWorker 'UdpProbeProtocol::Echo' 'UDP echo protocol selection is missing.'
Require-Match $networkWorker 'UdpProbeProtocol::Stun' 'UDP STUN fallback selection is missing.'
Require-Match $networkWorker 'runtime\.targetFailStreak >= 1' 'UDP primary must fall back after its first failed round.'
Require-Match $networkWorker 'kUdpPrimaryRetryIntervalMs = 15000' 'UDP recovery check must be fixed at 15 seconds.'
Require-Match $networkWorker 'kUdpPrimaryRecoverySuccesses = 3' 'UDP recovery must require three consecutive primary successes.'
Require-Match $networkWorker 'primaryRecoverySuccessStreak' 'UDP primary recovery success streak is missing.'
Require-Match $networkWorker 'ChannelIsIdle\(m_udpItem, cfg\) && runtime\.targetIndex == 0' 'UDP fallback recovery must bypass idle backoff.'
Require-Match $networkWorker 'cfg\.tcpTargetUrl' 'TCP worker target contract changed.'
Require-Match $networkWorker 'if \(m_tcpItem\.LastDrawTick\(\) == 0\)' 'Hidden TCP channel must not probe.'
Require-Match $networkWorker 'if \(m_udpItem\.LastDrawTick\(\) == 0\)' 'Hidden UDP channel must not probe.'
Require-Match $networkWorker 'fallbackVerified' 'UDP fallback verification state is missing.'
Require-Match $networkWorker 'fallbackAttempted' 'UDP fallback attempt state is missing.'
Require-Match $networkWorker 'onFallback && !runtime\.fallbackAttempted' 'Untried fallback must remain pending.'
Require-NoMatch $networkWorker 'PushQualityFailure' 'Primary Echo recovery must not contaminate the active STUN quality window.'
Require-Match $networkWorker 'ResetRuntime\(runtime, capacity, enabled, idle, targetKey\);\s+m_tcpProbe\.ResetTransport\(\);' 'TCP lifecycle changes must drop stale pooled transport.'
Require-Match $networkWorker 'ResetRuntime\(runtime, capacity, enabled, idle, targetKey\);\s+m_udpProbe\.ResetTransport\(\);' 'UDP lifecycle changes must drop stale socket transport.'
Require-Match $networkWorker 'ObserveLocalRoute' 'Probe workers must observe local route generation changes.'
Require-Match $networkWorker 'NetworkEpoch\(\)' 'Probe target keys must fold in the local network generation.'
Require-Match $networkWorker 'ProxyEpoch\(\)' 'TCP target keys must fold in the proxy identity generation.'
Require-Match (Read-ProjectFile 'shared_src\RoutePlan.cpp') 'shareProxyIdentityForUdp[\s\S]*?UdpRoute::Socks5' 'Split HTTP/SOCKS routes need an explicit same-upstream identity declaration.'
Require-Match $networkWorker 'ChannelTargetKey\(targets, proxyRoute, ChannelKind::Tcp\)[\s\S]*?ChannelTargetKey\(targets, proxyRoute, ChannelKind::Udp\)' 'TCP and UDP workers must derive channel-specific target keys.'
Require-Match $networkWorker 'idle && item\.ActivityEvent\(\)[\s\S]*?WaitForMultipleObjects' 'Idle waits must be event-driven and wake when the row becomes visible.'
Require-Match $networkWorker 'if \(routeChangedEvent && \(!idle \|\| item\.ActivityEvent\(\)\)\)' 'A missing row-activity event must fall back to bounded polling while idle.'
Require-Match $networkWorker 'NotifyIpInterfaceChange' 'Windows interface-change notification registration is missing.'
Require-Match $networkWorker 'NotifyRouteChange2' 'Windows route-table change notification registration is missing.'
Require-Match $networkWorker 'NotifyUnicastIpAddressChange' 'Windows source-address change notification registration is missing.'
Require-Match $networkWorker 'm_running\.store\(true[\s\S]*?m_tcpWorker = std::thread\(&CPluginNetwork::TcpWorkerLoop[\s\S]*?m_udpWorker = std::thread\(&CPluginNetwork::UdpWorkerLoop' 'Network workers must enter the running state before creating both member threads.'
Require-Match $networkWorker 'm_tcpProbe\.Cancel\(\)[\s\S]*?m_udpProbe\.Cancel\(\)[\s\S]*?m_primaryEchoProbe\.Cancel\(\)[\s\S]*?m_tcpWorker\.join\(\)[\s\S]*?m_udpWorker\.join\(\)' 'Network shutdown must cancel probes before joining both member workers.'
Require-NoMatch $networkWorker 'std::thread tcp|std::thread udp|std::move\(tcp\)|std::move\(udp\)|lock\.unlock\(\)|lock\.lock\(\)' 'The removed Network thread handoff layer returned.'
Require-NoMatch ($networkWorker + (Read-ProjectFile 'network_src\src\PluginNetwork.h')) 'm_started|WaitForActivation|runtime\.startTick|runtime\.initialized|TcpFallbackPolicy|UdpFallbackPolicy|IsAuthoritativeTcpTarget|DecideAfterProbe|DecideAfterPrimaryValidation' 'Removed Network lifecycle and one-line policy layers returned.'
Require-NoMatch ((Read-ProjectFile 'network_src\src\SlidingWindow.h') + $networkWorker) 'SlidingWindow\(\) \{ Resize\(30\); \}|int WindowCapacity\(const PluginConfig&' 'Removed eager window allocation or duplicate capacity formula returned.'
Require-NoMatch ($mergeHost + (Read-ProjectFile 'merge_src\PluginPingMerge.h')) 'CPluginPingMerge::Ping\(\)|CPluginPingMerge::Network\(\)|CPluginPingMerge::OnInitialize' 'Removed no-op merged forwarding methods returned.'
Require-Match $networkWorker 'InvalidateLocalRoute[\s\S]*?routeChangedEvent[\s\S]*?WaitForMultipleObjects' 'Idle waits must wake promptly when Windows reports an interface change.'
Require-Match $networkWorker 'if \(routeChangedEvent && \(!idle \|\| item\.ActivityEvent\(\)\)\)[\s\S]*?for \(;;\)[\s\S]*?static_cast<unsigned long long>\(1000\)[\s\S]*?item\.ActivityEvent\(\)' 'Notification or activity-event failure must retain interruptible one-second route polling.'
Require-Match (Read-ProjectFile 'network_src\src\NetworkStatusItem.cpp') 'm_lastDrawTick\.exchange\(now\)[\s\S]*?SetEvent\(m_activityEvent\)' 'A newly visible row must wake its idle worker.'
Require-Match $networkWorker 'copy = MakeTooltip\(\*snapshot, m_tcpItem\.LastDrawTick\(\) != 0,' 'Network tooltip must derive from the current snapshot and visible rows.'
Require-NoMatch ($networkWorker + (Read-ProjectFile 'network_src\src\PluginNetwork.h')) 'm_tooltip|m_tooltipMutex|RebuildTooltip|PublishInitialSnapshot|CPluginNetwork::OnInitialize' 'The removed Network cache and initialization layers returned.'
Require-Match $networkWorker 'const bool routeChanged = !runtime\.targetSetKey\.empty\(\) &&\s+runtime\.targetSetKey != targetKey;' 'A route change must be distinguished from a first round before the reset clears it.'
Require-Match $networkWorker 'runtime\.lastDiagnostic \+= L"; transport rebuilt after route change";[\s\S]*?runtime\.lastDiagnostic \+= L"; transport rebuilt after route change";' 'Both workers must report a rebuild where the probe result cannot clobber it.'
Require-Match $networkWorker 'route changed; rebuilding TCP transport[\s\S]*?route changed; rebuilding UDP transport' 'Both channels must publish an empty RTT window as soon as their route key changes.'
Require-Match $networkWorker 'ProbeGenerationChanged' 'Results crossing a route generation must be discarded.'
Require-Match $networkWorker 'UDP egress changed, transport rebuilt";\s+break;[\s\S]*?runtime\.window\.Push' 'A changed STUN egress must rebuild the UDP transport without pushing the transition result into the new window.'
Require-Match $networkWorker 'proxy node: [\s\S]*?epoch ' 'The debug log must record which node a measurement belongs to.'
Require-Match (Read-ProjectFile 'network_src\src\ChannelStatePolicy.h') 'fallbackPending' 'Channel state policy must model fallback warming explicitly.'
Require-Match (Read-ProjectFile 'network_src\src\ChannelStatePolicy.h') 'successCount == 0' 'Unsupported must be based on the current window.'
Require-Match $networkWorker 'void CPluginNetwork::TcpWorkerLoop\(\)[\s\S]*?while \(m_running\.load[\s\S]*?HandleWorkerFailure\(ChannelKind::Tcp\);[\s\S]*?WaitForSingleObject\(m_wake, kWorkerRetryBackoffMs\)' 'The TCP worker must keep retrying with an interruptible backoff while the plugin is running.'
Require-Match $networkWorker 'void CPluginNetwork::UdpWorkerLoop\(\)[\s\S]*?while \(m_running\.load[\s\S]*?HandleWorkerFailure\(ChannelKind::Udp\);[\s\S]*?WaitForSingleObject\(m_wake, kWorkerRetryBackoffMs\)' 'The UDP worker must keep retrying with an interruptible backoff while the plugin is running.'
Require-NoMatch $networkWorker 'kMaxWorkerRestarts|attempt \+ 1' 'A retry cap can leave m_running true after a channel worker exits permanently.'

$networkLoader = Read-ProjectFile 'network_src\src\ConfigManager.cpp'
Require-Match $networkLoader 'c\.tcpTargetUrl = L"https://www\.google\.com/generate_204"' 'Google must remain authoritative for TCP.'
Require-Match $networkLoader 'kIniFileName = L"PluginPing\.ini"' 'Network config must retain the PluginPing name.'
Require-NoMatch $networkLoader 'pluginnetwork\.ini|kLegacyIniFileName|NormalizeIniFileNameCase' 'Legacy network config migration returned.'

$udpProbe = Read-ProjectFile 'network_src\src\StunProbe.cpp'
Require-Match $udpProbe 'size != requestSize \|\| memcmp\(message, request, requestSize\) != 0' 'UDP echo must validate an exact echoed payload.'
Require-Match $udpProbe 'void UdpProbe::ResetTransport\(\)[\s\S]*?m_resolved = false;[\s\S]*?m_lastResolveTick = 0;' 'A transport reset must drop the address cached under the previous route.'
Require-Match (Read-ProjectFile 'network_src\src\StunProbe.h') 'class UdpProbe' 'UDP transport still exposes the obsolete STUN-only class name.'

$project = Read-ProjectFile 'PluginPing.vcxproj'
Require-Match $project 'PLUGINPING_MERGED' 'Child export suppression is missing.'
Require-Match $project 'ping_ConfigManager\.obj' 'Ping object names are not isolated.'
Require-Match $project 'network_ConfigManager\.obj' 'Network object names are not isolated.'
Require-Match $project '<TargetName>PluginPing</TargetName>' 'The DLL target must be PluginPing.'
Require-Match $project '<None Include="PluginPing\.ini">' 'PluginPing.ini is not deployed.'
Require-Match $project 'merge_src\\CompositeStatusItem\.cpp' 'Composite row source is missing from the project.'
Require-Match $project 'shared_src\\RoutePlan\.cpp' 'Shared route plan source is missing from the project.'
Require-Match $project 'shared_src\\RouteEpoch\.cpp' 'Shared route epoch source is missing from the project.'
Require-Match $project 'shared_src\\HostDrawing\.h' 'Shared host drawing state is missing from the project.'
Require-NoMatch $project 'pluginnetwork\.ini|MmdbReader|network_src\\include' 'Old config, MMDB, or duplicate include tree remains in the project.'

$ipItem = Read-ProjectFile 'ping_src\src\PingStatusItem.cpp'
$networkItem = Read-ProjectFile 'network_src\src\NetworkStatusItem.cpp'
$networkRenderer = Read-ProjectFile 'network_src\src\Renderer.cpp'
$metricsData = Read-ProjectFile 'network_src\src\MetricsData.h'
$hostDrawing = Read-ProjectFile 'shared_src\HostDrawing.h'
Require-Match $ipItem 'MarkDisplayed\(\)' 'IP visibility signal is missing.'
Require-Match $ipItem 'GetEndpointWidthEx[\s\S]*?MeasureSnapshotWidth' 'DIRECT and PROXY must use one shared IP-section geometry.'
Require-Match $ipItem 'const int candidate = measured;' 'Composite IP width must not include the standalone Width floor.'
Require-NoMatch $ipRenderer '\bipPad\b' 'IP/probe spacing must not reintroduce a second tail padding term.'
Require-Match $ipRenderer 'm\.gap\s*=\s*\(std::max\)\(1, TextWidth\(dc, L" "\)\)' 'IP group internals must use one measured host-font space.'
Require-Match $ipRenderer 'displayAsnOnly' 'PROXY loc=CN must suppress the second IP placeholder.'
Require-NoMatch $ipRenderer '\brightPad\b' 'IP renderer must not own the composite section gap.'
Require-Match $networkRenderer 'if \(showLabel\)' 'Embedded TCP/UDP labels are not suppressible.'
Require-Match (Read-ProjectFile 'network_src\src\PluginNetwork.cpp') 'SetEmbeddedMode\(true\)' 'Merged network items must use embedded layout.'
Require-Match ($ipRenderer + $networkRenderer) 'SaveDC' 'Renderers must preserve the host HDC.'
Require-Match ($ipRenderer + $networkRenderer) 'DrawTextW' 'Renderers must use the host-hookable DrawTextW import.'
Require-NoMatch ($ipRenderer + $pingConfig + (Read-ProjectFile 'PluginPing.ini')) 'IpFontWeight' 'IP text must use the normal shared font weight.'
Require-Match $hostDrawing 'GetCurrentObject\(dc, OBJ_FONT\)' 'Renderers must inherit the font selected by TrafficMonitor.'
Require-Match $hostDrawing 'GetTextColor\(dc\)' 'Renderers must inherit TrafficMonitor normal text colour.'
Require-Match $ipRenderer 'CaptureHostFont\(hDC\)[\s\S]*?HostTextColor\(hDC' 'IP rendering must consume host typography and colour.'
Require-Match $networkRenderer 'CaptureHostFont\(hDC\)[\s\S]*?HostTextColor\(hDC' 'RTT/JIT rendering must consume host typography and colour.'
Require-NoMatch ($ipRenderer + $networkRenderer) 'CreateFontIndirectW|GetGdiResourceCache' 'A renderer-local font source returned.'
Require-Match $networkRenderer 'DrawTextIn\(hDC, L"RTT:",[\s\S]*?palette\.text, DT_LEFT\)' 'RTT label must use normal left-aligned text.'
Require-Match $networkRenderer 'DrawTextIn\(hDC, L"JIT:",[\s\S]*?palette\.text, DT_LEFT\)' 'JIT label must use normal left-aligned text.'
Require-Match $networkRenderer 'DrawTextIn\(hDC, latency,[\s\S]*?rttColor, DT_LEFT\)' 'RTT value must be left-aligned and own the former status accent.'
Require-Match $networkRenderer 'ToneForLatencyValue\(channel\.avgRttMs\)[\s\S]*?ToneForLatencyValue\(channel\.jitterMs\)' 'RTT and JIT must evaluate the numeric latency bands independently.'
Require-Match $networkRenderer 'DrawTextIn\(hDC, jitter,[\s\S]*?jitterColor, DT_LEFT\)' 'JIT must use its independently resolved colour.'
Require-NoMatch $networkRenderer 'DrawTextIn\(hDC, jitter,[\s\S]*?rttColor, DT_LEFT\)' 'JIT must not inherit the RTT colour variable.'
Require-Match $metricsData 'ToneForLatencyValue[\s\S]*?valueMs <= 70[\s\S]*?QualityTone::Good[\s\S]*?valueMs <= 149[\s\S]*?QualityTone::Warn[\s\S]*?QualityTone::Bad' 'RTT and JIT must share the PluginPing 70/150 ms colour boundaries.'
Require-Match $networkRenderer 'baselineRttCell\s*=\s*TextWidth\(dc, cfg\.compactMode \? L"999" : L"999 ms"\)' 'RTT must reserve one native-style value-and-unit cell.'
Require-Match $networkRenderer 'layout\.rttCell\s*=\s*\(std::max\)\(measuredRttCell, baselineRttCell\)' 'RTT cell must use its stable baseline width.'
Require-Match $networkRenderer 'layout\.jitterValue\s*=\s*\(std::max\)\(measuredJitter, baselineJitter\)' 'Jitter column must reserve its three-digit baseline width.'
Require-Match $networkRenderer 'baselineJitter\s*=\s*TextWidth\(dc, L"999"\)' 'Jitter column must remain stable throughout the 1-999 ms range.'
Require-Match $metricsData 'if \(valueMs < 0\)[\s\S]*?QualityTone::Neutral' 'An unavailable RTT or JIT value must remain neutral.'
Require-Match $networkRenderer 'DrawTextIn\(hDC, latency,[\s\S]*?DrawTextIn\(hDC, L"ms",[\s\S]*?DrawTextIn\(hDC, L"JIT:"' 'The RTT unit must precede the JIT field.'
Require-Match $networkRenderer 'cursor = rttCellLeft \+ layout\.rttCell \+ layout\.fieldGap' 'JIT must use a fixed row-aligned cell origin.'
Require-NoMatch ($networkRenderer + $networkItem + $networkWorker) '(?-i:\bJit\b)' 'Visible jitter labels must use JIT casing consistently.'
Require-Match $networkRenderer 'ComputeColumns\(hDC, hostFont\.handle, hostFont\.handle, metrics,[\s\S]*?showLabel, kind, false\)' 'DIRECT and PROXY must draw with shared probe column widths.'
Require-Match $networkRenderer 'if \(!showLabel\)[\s\S]*?metrics\.leftPad = 0;[\s\S]*?metrics\.rightPad = 0;' 'Embedded probe padding must be removed.'
Require-NoMatch $networkRenderer 'PercentText|layout\.percent|L"100%"|L"--%"' 'Inline stability percentage must remain removed.'
Require-NoMatch $networkRenderer 'FillCircle|Ellipse|CircleEntry|showStatusDot|plusMinus|L"\\u00B1"' 'The obsolete status dot or plus/minus layout returned.'
Require-NoMatch ($ipItem + $networkItem) 'GetItemValueText\(\) const\s*\{\s*return nullptr' 'Custom text getters must never return null.'
Require-Match $networkLoader 'written == expected' 'Default INI writes must reject short writes.'

$ini = Read-ProjectFile 'PluginPing.ini'
Require-Match $ini '\[IP\][\s\S]*DirectResolveIntervalMs=10000' 'Merged INI is missing IP settings.'
Require-Match $ini '\[IP\][\s\S]*ProxyResolveIntervalMs=1000' 'Merged INI is missing fast PROXY refresh settings.'
Require-Match $ini 'ConfigVersion=2' 'Merged INI must opt out of the legacy 5-second default migration.'
Require-Match $ini 'ShareProxyIdentityForUdp=false' 'Merged INI must expose the explicit split-proxy identity policy.'
Require-Match $ini '\[Style\][\s\S]*Typography follows TrafficMonitor' 'Host-owned typography is not documented in the INI.'
Require-NoMatch ($pingConfig + $networkConfig + $networkLoader + $ipRenderer + $networkRenderer + $ini) 'FontName|FontSize|fontName|fontSize' 'A second plugin-owned typography source returned.'
Require-NoMatch ($networkConfig + $networkLoader + $networkItem + $networkRenderer + $ini) 'ShowStatusDot|showStatusDot' 'Removed status-dot configuration returned.'
Require-Match $ini 'PluginPing 1\.0\.14' 'Bundled INI version must match the merged product.'

$versionResource = Read-ProjectFile 'merge_src\PluginPing.rc'
$pingVersionResource = Read-ProjectFile 'ping_src\src\PluginPing.rc'
$networkVersionResource = Read-ProjectFile 'network_src\src\PluginNetwork.rc'
$pingCommon = Read-ProjectFile 'ping_src\src\Common.h'
$networkCommon = Read-ProjectFile 'network_src\src\Common.h'
Require-Match $mergeHost 'case TMI_VERSION:\s+return L"1\.0\.14"' 'Host-reported version must be 1.0.14.'
Require-Match $versionResource 'FILEVERSION\s+1,0,14,0' 'Windows file version must be 1.0.14.0.'
Require-Match $versionResource 'VALUE "FileVersion", "1\.0\.14"' 'Windows version string must be 1.0.14.'
Require-Match $pingVersionResource 'FILEVERSION\s+1,0,14,0' 'IP child file version drifted.'
Require-Match $networkVersionResource 'FILEVERSION\s+1,0,14,0' 'Network child file version drifted.'
Require-Match $pingCommon 'kPluginPingVersion\[\]\s*=\s*L"1\.0\.14"' 'IP host version drifted.'
Require-Match $networkCommon 'kPluginNetworkVersion\[\]\s*=\s*L"1\.0\.14"' 'Network host version drifted.'
Require-Match $pingCommon 'kPluginPingUserAgent\[\]\s*=\s*L"PluginPing/1\.0\.14"' 'IP User-Agent version drifted.'
Require-Match $networkCommon 'kPluginNetworkUserAgent\[\]\s*=\s*L"PluginPing/1\.0\.14"' 'TCP User-Agent version drifted.'
Require-Match $pingCommon '(?s)#include <winsock2\.h>.*#include <windows\.h>' 'IP headers must include Winsock2 before Windows.'
Require-NoMatch $pingCommon 'ipexport|icmpapi|iphlpapi' 'Removed ICMP dependencies must not return.'

$routePlan = Read-ProjectFile 'shared_src\RoutePlan.cpp'
Require-Match $routePlan 'Auto deliberately follows only an enabled static user proxy' 'Auto route semantics are not documented in code.'
Require-Match $routePlan 'HttpRoute::Unavailable' 'Proxy routes must fail closed when unusable.'
Require-Match $routePlan 'ResolveRoutePlan' 'HTTP/TCP/UDP route resolution is not shared.'
Require-Match $routePlan 'SharesNamedProxyEndpoint' 'HTTP and UDP must share proxy identity only when their normalized endpoints match.'

Write-Output 'PluginPing composite contract checks passed.'
